import {useEffect,useState} from 'react';import {Upload,RefreshCw,Server,Database,Brain} from 'lucide-react';import {api} from '../services/api';import StatusPill from '../components/StatusPill'
export default function Admin(){const[health,setHealth]=useState(null),[matrix,setMatrix]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false)
 async function load(){try{setHealth(await api.healthDetails());setMatrix(await api.matrix())}catch(e){setMsg(e.message)}}useEffect(()=>{load()},[])
 async function upload(e){const file=e.target.files?.[0];if(!file)return;setBusy(true);setMsg('Validating and indexing new Matrix…');try{await api.upload(file);setMsg('New Matrix activated successfully.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false);e.target.value=''}}
 async function reindex(){setBusy(true);setMsg('Rebuilding local semantic index…');try{await api.reindex();setMsg('Index rebuilt.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}}
 return <div className="admin-page"><div className="page-title"><div><span className="eyebrow">SERVER CONTROL</span><h2>Admin</h2></div></div>
 <div className="admin-grid"><article><Server/><span>Backend</span><b>{health?.backend||'Checking…'}</b><StatusPill ok={health?.backend==='online'} label={health?.backend==='online'?'Online':'Offline'}/></article><article><Brain/><span>Ollama</span><b>{health?.model||'—'}</b><StatusPill ok={health?.ollama==='online'} label={health?.ollama||'Checking…'}/></article><article><Database/><span>Matrix Rules</span><b>{matrix?.rule_count??'—'}</b><StatusPill ok={matrix?.index_ready} label={matrix?.index_ready?'Index ready':'Index pending'}/></article></div>
 <div className="admin-card"><h3>Current Matrix</h3><dl><div><dt>Filename</dt><dd>{matrix?.filename||'None loaded'}</dd></div><div><dt>Sheets</dt><dd>{matrix?.sheet_count??'—'}</dd></div><div><dt>Rules / records</dt><dd>{matrix?.rule_count??'—'}</dd></div><div><dt>Activated</dt><dd>{matrix?.activated_at?new Date(matrix.activated_at).toLocaleString():'—'}</dd></div></dl><div className="admin-actions"><label className="button"><Upload size={17}/>Replace Matrix<input type="file" accept=".xlsx" hidden disabled={busy} onChange={upload}/></label><button className="button secondary" disabled={busy} onClick={reindex}><RefreshCw size={17}/>Rebuild Index</button></div>{msg&&<div className="notice">{msg}</div>}<p className="warning">A replacement becomes active only after validation and local semantic indexing succeed. If it fails, the current Matrix stays active.</p></div>
 </div>}
